; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
platform_packages =
	framework-arduinoespressif32@3.20014.231204
build_src_filter =
	+<*>
	-<test/>
lib_deps = 
	thijse/ArduinoLog@^1.1.1
	adafruit/Adafruit ADS1X15@^2.4.0
	SPI
	adafruit/Adafruit LSM6DS@^4.7.3
	adafruit/Adafruit Unified Sensor@^1.1.14
	adafruit/RTClib@^2.1.4
build_flags = -I include

[env:sd_card_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/sdCardTest.cpp>

[env:telemetry_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/telemetryTest.cpp>

[env:i2c_scan_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/i2cScanTest.cpp>

[env:idle_power_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/idlePowerTest.cpp>

[env:gpio4_toggle_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/gpio4ToggleTest.cpp>

[env:rtc_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/rtcTest.cpp>

[env:rtc_set_time_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/rtcSetTimeTest.cpp>

[env:can_transceiver_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/canTransceiverTest.cpp>

[env:can_no_ack_transceiver_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/canNoAckTransceiverTest.cpp>

[env:can_simple_send_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/canSimpleSendTest.cpp>

[env:can_internal_loopback_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/canInternalLoopbackTest.cpp>

[env:can_receive_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/canReceiveTest.cpp>

[env:can_dump_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/canDumpTest.cpp>

[env:suspension_sensor_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/suspensionSensorTest.cpp>

[env:steering_angle_sensor_test]
extends = env:esp32dev
build_src_filter =
	-<*>
	+<test/steeringAngleSensorTest.cpp>
